#!/bin/bash
FSTAB="/etc/fstab"
CRONTAB_DIR="/var/spool/cron/crontabs"
CRONTAB_ROOT="/var/spool/cron/crontabs/root"

# HDD 8TB
USB_DEV_8T_1="/dev/sdb1"
MOUNT_PATH_8T_1="/media/hdd-8T-1"

# HDD 8TB
USB_DEV_8T_3="/dev/sdc1"
MOUNT_PATH_8T_3="/media/hdd-8T-3"

# HDD 16TB
USB_DEV_16T_4="/dev/sdd1"
MOUNT_PATH_8T_3="/media/hdd-8T-3"

# BACKUP
PH_BACKUP="${MOUNT_PATH_8T_1}/backup"
# MEDIA
PH_MEDIA="${MOUNT_PATH_8T_1}/media"

# MY ROOT FOLDER
MYSVIT="/mysvit"
MYSVIT_BACKUP="${MYSVIT}/backup"
MYSVIT_MEDIA="${MYSVIT}/media"
MYSVIT_DELUGE="${MYSVIT}/deluge"
MYSVIT_DELUGE_TORRENTS="${MYSVIT_DELUGE}/torrents"
MYSVIT_DELUGE_DOWNLOAD="${MYSVIT_DELUGE}/download"
MYSVIT_DELUGE_COMPLEATED="${MYSVIT_DELUGE}/compleated"
MYSVIT_WORK="${MYSVIT}/work"
MYSVIT_LOG="/var/log/mysvit"

# MY MEDIA FOLDERS
MYSVIT_AUDIO="${MYSVIT_MEDIA}/audio"
MYSVIT_AUTOEXEC="${MYSVIT_MEDIA}/autoexec"
MYSVIT_BOOKS="${MYSVIT_MEDIA}/books"
MYSVIT_CARTOONS="${MYSVIT_MEDIA}/cartoons"
MYSVIT_MOVIES="${MYSVIT_MEDIA}/movies"
MYSVIT_MOVIES_ALL="${MYSVIT_MEDIA}/movies/all"
MYSVIT_MOVIES_DOCUMENTARY="${MYSVIT_MEDIA}/movies/documentary"
MYSVIT_MOVIES_SCI_FI="${MYSVIT_MEDIA}/movies/sci-fi"
MYSVIT_MY_PHOTO="${MYSVIT_MEDIA}/my-photo"
MYSVIT_MY_PRIVATE="${MYSVIT_MEDIA}/my-private"
MYSVIT_MY_VIDEO="${MYSVIT_MEDIA}/ my-video"
MYSVIT_ORIGINALS="${MYSVIT_MEDIA}/originals"
MYSVIT_RECORDERD_AUDIO="${MYSVIT_MEDIA}/recorderd-audio"


PH_MYSVIT_AUDIO="${MOUNT_PATH_8T_1}/media/audio"
PH_MYSVIT_AUTOEXEC="${MOUNT_PATH_8T_1}/media/autoexec"
PH_MYSVIT_BOOKS="${MOUNT_PATH_8T_1}/media/books"
PH_MYSVIT_CARTOONS="${MOUNT_PATH_8T_1}/media/cartoons"
PH_MYSVIT_MOVIES="${MOUNT_PATH_8T_1}/media/movies"
PH_MYSVIT_MOVIES_ALL="${MOUNT_PATH_8T_1}/media/movies/all"
PH_MYSVIT_MOVIES_DOCUMENTARY="${MOUNT_PATH_8T_1}/media/movies/documentary"
PH_MYSVIT_MOVIES_SCI_FI="${MOUNT_PATH_8T_2}/media/movies/sci-fi"
PH_MYSVIT_MY_PHOTO="${MOUNT_PATH_8T_1}/media/my-photo"
PH_MYSVIT_MY_PRIVATE="${MOUNT_PATH_8T_1}/media/my-private"
PH_MYSVIT_MY_VIDEO="${MOUNT_PATH_8T_1}/media/ my-video"
PH_MYSVIT_ORIGINALS="${MOUNT_PATH_8T_1}/media/originals"
PH_MYSVIT_RECORDERD_AUDIO="${MOUNT_PATH_8T_1}/media/recorderd-audio"
