#!/bin/bash
source ./my/my-config.sh

apt update
apt install -y zip
apt install -y unzip

mkdir $MYSVIT

rm $MYSVIT_BACKUP
ln -s $PH_BACKUP $MYSVIT_BACKUP

mkdir $MYSVIT_MEDIA
mkdir $MYSVIT
mkdir $MYSVIT_MOVIES

ln -s $PH_MYSVIT_AUDIO $MYSVIT_AUDIO
ln -s $PH_MYSVIT_AUTOEXEC $MYSVIT_AUTOEXEC
ln -s $PH_MYSVIT_BOOKS $MYSVIT_BOOKS
ln -s $PH_MYSVIT_CARTOONS $MYSVIT_CARTOONS
ln -s $PH_MYSVIT_MOVIES_ALL $MYSVIT_MOVIES_ALL
ln -s $PH_MYSVIT_MOVIES_DOCUMENTARY $MYSVIT_MOVIES_DOCUMENTARY
ln -s $PH_MYSVIT_MOVIES_SCI-FI $MYSVIT_MOVIES_SCI-FI
ln -s $PH_MYSVIT_MY-PHOTO $MYSVIT_MY-PHOTO
ln -s $PH_MYSVIT_MY-PRIVATE $MYSVIT_MY-PRIVATE
ln -s $PH_MYSVIT_MY-VIDEO $MYSVIT_MY-VIDEO
ln -s $PH_MYSVIT_ORIGINALS $MYSVIT_ORIGINALS
ln -s $PH_MYSVIT_RECORDERD-AUDIO $MYSVIT_RECORDERD-AUDIO

mkdir $MYSVIT_DELUGE
mkdir $MYSVIT_DELUGE_TORRENTS
mkdir $MYSVIT_DELUGE_DOWNLOAD
mkdir $MYSVIT_DELUGE_COMPLEATED
mkdir $MYSVIT_WORK
#rm $MYSVIT_DELUGE_DOWNLOAD
#ln -s $MOUNT_PATH_500G_1 $MYSVIT_DELUGE_DOWNLOAD
